"""Assign strand information to RNA SNVs."""

# %%
import logging
import pickle
from pathlib import Path

import pandas as pd
import polars as pl
import pyranges as pr
import vcfpy
from genomicranges import GenomicRanges


# %%
def configure_logger(console_output=None, log_file=None, log_level="INFO"):
    logger = logging.getLogger()

    log_levels = {
        "CRITICAL": logging.CRITICAL,
        "ERROR": logging.ERROR,
        "WARNING": logging.WARNING,
        "INFO": logging.INFO,
        "DEBUG": logging.DEBUG,
        "NOTSET": logging.NOTSET,
    }

    log_level_constant = log_levels.get(log_level.upper(), logging.INFO)
    logger.setLevel(log_level_constant)

    formatter = logging.Formatter(
        "%(levelname)s [%(asctime)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )

    if logger.hasHandlers():
        logger.handlers.clear()

    if console_output:
        ch = logging.StreamHandler()
        ch.setLevel(log_level_constant)
        ch.setFormatter(formatter)
        logger.addHandler(ch)

    if log_file:
        fh = logging.FileHandler(log_file)
        fh.setLevel(log_level_constant)
        fh.setFormatter(formatter)
        logger.addHandler(fh)


# %%
def iter_vcf_rows(vcf_path: Path, sample_name: str):
    """Iterate over VCF records and extract F1R2/F2R1 strand-specific allele
    counts.

    Parses a VCF file and extracts strand orientation information (F1R2 and F2R1
    counts) for each variant. These counts represent read pairs in different
    orientations and are used to infer the transcriptional strand.

    F1R2/F2R1 counts are typically generated by variant callers like GATK
    Mutect2 and indicate:
    - F1R2: Read1 forward, Read2 reverse orientation
    - F2R1: Read1 reverse, Read2 forward orientation

    Records without F1R2/F2R1 annotations are skipped. For multi-allelic sites,
    each alternate allele is yielded as a separate row.

    Args:
        vcf_path (Path): Path to the VCF file to parse.
        sample_name (str): Name of the sample in the VCF file to extract data
            from.

    Yields:
        tuple: A 9-element tuple containing:
            - chrom (str): Chromosome name
            - pos (int): Variant position (1-based)
            - vcf_id (str): VCF ID field
            - ref (str): Reference allele
            - alt (str): Alternate allele
            - f1r2_ref (int): F1R2 count for reference allele
            - f1r2_alt (int): F1R2 count for alternate allele
            - f2r1_ref (int): F2R1 count for reference allele
            - f2r1_alt (int): F2R1 count for alternate allele
    """
    idx_ref = 0
    with vcfpy.Reader.from_path(vcf_path) as reader:
        for record in reader:
            chrom = record.CHROM  # type: ignore
            pos = record.POS  # type: ignore
            vcf_id = record.ID[0]  # type: ignore
            ref = record.REF  # type: ignore
            alts = record.ALT  # type: ignore
            # f1r2 = record.calls[0].data.get("F1R2")  # type: ignore
            # f2r1 = record.calls[0].data.get("F2R1")  # type: ignore
            f1r2 = record.call_for_sample[sample_name].data.get("F1R2")  # type: ignore
            f2r1 = record.call_for_sample[sample_name].data.get("F2R1")  # type: ignore
            if f1r2 is None or f2r1 is None:
                continue
            for i, _alt in enumerate(alts):
                idx_alt = i + 1
                yield (
                    chrom,
                    pos,
                    vcf_id,
                    ref,
                    _alt.value,  # type: ignore
                    f1r2[idx_ref],
                    f1r2[idx_alt],
                    f2r1[idx_ref],
                    f2r1[idx_alt],
                )


def get_vcf_data(vcf_path, sample_name):
    """Extract VCF data and calculate strand bias metrics from F1R2/F2R1 counts.

    Processes VCF file to create a DataFrame with variant information and
    computed strand bias metrics. Calculates two key percentages:

    1. pct_f1r2: Proportion of all reads in F1R2 orientation
        = (F1R2_ref + F1R2_alt) / (F1R2_ref + F1R2_alt + F2R1_ref + F2R1_alt)

    2. pct_f1r2_alt: Proportion of alternate allele reads in F1R2 orientation
        = F1R2_alt / (F1R2_alt + F2R1_alt)

    Strand interpretation depends on library strandedness:
    - fr-firststrand (ISR): high pct_f1r2 → - strand, low → + strand
    - fr-secondstrand (ISF): high pct_f1r2 → + strand, low → - strand
    - unstranded: pct_f1r2 not used for strand inference

    Args:
        vcf_path (Path): Path to the VCF file.
        sample_name (str): Name of the sample in the VCF file.

    Returns:
        pl.DataFrame: Polars DataFrame with columns:
            - chrom, pos, id, ref, alt: Variant identifiers
            - n_f1r2_ref, n_f1r2_alt: F1R2 counts for ref/alt alleles
            - n_f2r1_ref, n_f2r1_alt: F2R1 counts for ref/alt alleles
            - pct_f1r2: Overall F1R2 percentage
            - pct_f1r2_alt: F1R2 percentage for alternate allele only
            - no_reads: Flag indicating no read coverage
            - no_reads_alt: Flag indicating no alternate allele reads
    """
    schema = {
        "chrom": pl.Utf8,
        "pos": pl.Int64,
        "id": pl.Utf8,
        "ref": pl.Utf8,
        "alt": pl.Utf8,
        "n_f1r2_ref": pl.Int64,
        "n_f1r2_alt": pl.Int64,
        "n_f2r1_ref": pl.Int64,
        "n_f2r1_alt": pl.Int64,
    }
    rows = list(iter_vcf_rows(vcf_path, sample_name))
    if not rows:
        return pl.DataFrame(
            schema={
                **schema,
                "pct_f1r2": pl.Float64,
                "pct_f1r2_alt": pl.Float64,
                "no_reads": pl.Boolean,
                "no_reads_alt": pl.Boolean,
            }
        )
    df = pl.DataFrame(rows, schema=schema, orient="row")

    df = df.with_columns(
        (
            (pl.col("n_f1r2_ref") + pl.col("n_f1r2_alt"))
            / (
                pl.col("n_f1r2_ref")
                + pl.col("n_f1r2_alt")
                + pl.col("n_f2r1_ref")
                + pl.col("n_f2r1_alt")
            )
        ).alias("pct_f1r2"),
        (pl.col("n_f1r2_alt") / (pl.col("n_f1r2_alt") + pl.col("n_f2r1_alt"))).alias(
            "pct_f1r2_alt"
        ),
    ).with_columns(
        pl.when(pl.col("pct_f1r2").is_nan())
        .then(True)
        .otherwise(False)
        .alias("no_reads"),
        pl.when(pl.col("pct_f1r2_alt").is_nan())
        .then(True)
        .otherwise(False)
        .alias("no_reads_alt"),
    )

    return df


# %%
def get_strand(vcf_grs: GenomicRanges, gtf_grs: GenomicRanges):
    """Determine strand information for variants by overlapping with GTF
    annotations.

    For each variant position, finds overlapping transcript features from the
    GTF and extracts their strand annotations. When a variant overlaps multiple
    transcripts, both the complete set of strands and the majority (mode) strand
    are reported. Variants with no transcript overlap are assigned "." for both
    strand columns.

    Strand assignment scenarios:
    - Single transcript overlap: Unambiguous strand assignment (+ or -)
    - Multiple transcripts, same strand: Unambiguous strand assignment
    - Multiple transcripts, different strands: Ambiguous (e.g., "+,-" or ".,+")
    - No transcript overlap: Missing strand (".")

    Args:
        vcf_grs (GenomicRanges): GenomicRanges object containing variant
            positions.
        gtf_grs (GenomicRanges): GenomicRanges object containing GTF transcript
            features with strand annotations.

    Returns:
        pl.DataFrame: Polars DataFrame with columns:
            - index: Row index from original variant data
            - strand_all: Comma-separated list of all unique strands (sorted),
              "." for variants with no transcript overlap
            - strand_majority: Comma-separated list of most frequent strand(s)
              (sorted), "." for variants with no transcript overlap
    """
    all_indices = pl.DataFrame(
        {"index": pl.Series(range(len(vcf_grs)), dtype=pl.UInt32)}
    )

    hits = gtf_grs.find_overlaps(vcf_grs, ignore_strand=True)
    hit_query = hits["query_hits"]
    hit_self = hits["self_hits"]
    strands_gtf = gtf_grs.get_strand(as_type="list")

    df_hits = pl.DataFrame(
        {
            "index": hit_query,
            "strand": [strands_gtf[i] for i in hit_self],  # type: ignore
        }
    )

    df_strand = (
        df_hits.group_by("index")
        .agg(
            pl.col("strand").unique().alias("strand_list"),
            pl.col("strand").mode().alias("strand_mode_list"),
        )
        .with_columns(
            pl.col("strand_list")
            .map_elements(lambda lst: ",".join(sorted(lst)), return_dtype=pl.Utf8)
            .alias("strand_all"),
            pl.col("strand_mode_list")
            .map_elements(lambda lst: ",".join(sorted(lst)), return_dtype=pl.Utf8)
            .alias("strand_majority"),
        )
        .select(["index", "strand_all", "strand_majority"])
    )

    return all_indices.join(df_strand, on="index", how="left").with_columns(
        pl.col("strand_all").fill_null("."),
        pl.col("strand_majority").fill_null("."),
    )


# %%
# *--------------------------------------------------------------------------* #
# * Strandedness mapping (F1R2/F2R1 to transcriptional strand):              * #
# *   fr-firststrand (Salmon ISR): F1R2 = -, F2R1 = +                        * #
# *   fr-secondstrand (Salmon ISF): F1R2 = +, F2R1 = -                       * #
# *   unstranded: no strand inference from F1R2/F2R1                         * #
# *--------------------------------------------------------------------------* #
def _get_strand_mapping(strandedness):
    """Return (high_f1r2_strand, low_f1r2_strand) for a given strandedness.

    Args:
        strandedness (str): One of "fr-firststrand", "fr-secondstrand", or
        "unstranded".

    Returns:
        tuple or None: (strand_when_high_f1r2, strand_when_low_f1r2), or None
        for unstranded.
    """
    if strandedness == "fr-firststrand":
        return ("-", "+")
    elif strandedness == "fr-secondstrand":
        return ("+", "-")
    elif strandedness == "unstranded":
        return None
    else:
        raise ValueError(
            f"Unknown strandedness: {strandedness!r}. "
            "Expected 'fr-firststrand', 'fr-secondstrand', or 'unstranded'."
        )


def _clarify_strand(input_col, new_col, f1r2_pct_col, rate, strandedness):
    """Helper function to clarify ambiguous strand assignments using F1R2/F2R1
    bias.

    When GTF annotation doesn't provide a clear strand (not + or -), uses the
    F1R2/F2R1 ratio to infer the strand based on the library strandedness.

    For fr-firststrand (ISR):
    - pct_f1r2 >= rate: Assign - strand
    - pct_f1r2 <= (1-rate): Assign + strand

    For fr-secondstrand (ISF):
    - pct_f1r2 >= rate: Assign + strand
    - pct_f1r2 <= (1-rate): Assign - strand

    For unstranded: Keep original strand (no clarification).

    Args:
        input_col (str): Name of input column with strand information from GTF.
        new_col (str): Name of output column for clarified strand.
        f1r2_pct_col (str): Name of column with F1R2 percentage (0 to 1).
        rate (float): Threshold rate for strong strand bias (typically 0.9).
        strandedness (str): Library strandedness type.

    Returns:
        pl.Expr: Polars expression for strand clarification that can be used
            in with_columns().
    """
    mapping = _get_strand_mapping(strandedness)
    if mapping is None:
        return pl.col(input_col).alias(new_col)

    high_strand, low_strand = mapping
    return (
        pl.when(
            (~pl.col(input_col).is_in(["+", "-"])) & (pl.col(f1r2_pct_col) >= rate)
        )
        .then(pl.lit(high_strand))
        .when(
            (~pl.col(input_col).is_in(["+", "-"]))
            & (pl.col(f1r2_pct_col) <= (1 - rate))
        )
        .then(pl.lit(low_strand))
        .otherwise(pl.col(input_col))
        .alias(new_col)
    )


def clarify_strand(
    df: pl.DataFrame, bias_rate: float = 0.9, strandedness: str = "fr-firststrand"
):
    """Clarify strand assignments using F1R2/F2R1 bias when GTF annotation is
    ambiguous.

    Applies strand clarification to both the complete strand list (strand_all)
    and the majority strand (strand_majority), using both overall F1R2
    percentage (pct_f1r2) and alternate allele-specific F1R2 percentage
    (pct_f1r2_alt).

    This generates four new columns with clarified strand information, allowing
    comparison between different clarification strategies.

    Args:
        df (pl.DataFrame): Polars DataFrame with variant and strand information,
            including strand_all, strand_majority, pct_f1r2, and pct_f1r2_alt
            columns.
        bias_rate (float, optional): Threshold for considering strand bias
            significant. Default is 0.9, meaning ≥90% reads in one orientation
            is required.
        strandedness (str, optional): Library strandedness type. One of
            "fr-firststrand", "fr-secondstrand", or "unstranded". Default is
            "fr-firststrand".

    Returns:
        pl.DataFrame: DataFrame with four additional columns:
            - strand_all_clarified: Clarified using strand_all and pct_f1r2
            - strand_all_clarified_alt: Clarified using strand_all and pct_f1r2_alt
            - strand_majority_clarified: Clarified using strand_majority and pct_f1r2
            - strand_majority_clarified_alt: Clarified using strand_majority and pct_f1r2_alt
    """
    return df.with_columns(
        _clarify_strand(
            "strand_all", "strand_all_clarified", "pct_f1r2", bias_rate, strandedness
        ),
        _clarify_strand(
            "strand_all",
            "strand_all_clarified_alt",
            "pct_f1r2_alt",
            bias_rate,
            strandedness,
        ),
        _clarify_strand(
            "strand_majority",
            "strand_majority_clarified",
            "pct_f1r2",
            bias_rate,
            strandedness,
        ),
        _clarify_strand(
            "strand_majority",
            "strand_majority_clarified_alt",
            "pct_f1r2_alt",
            bias_rate,
            strandedness,
        ),
    )


def _detect_conflict(input_col, new_col, f1r2_pct_col, rate, strandedness):
    """Helper function to detect conflicts between GTF strand and F1R2/F2R1 bias.

    A conflict occurs when the strand-specific read orientation (F1R2/F2R1 bias)
    contradicts the GTF-assigned strand.

    For fr-firststrand (ISR):
    - pct_f1r2 >= rate AND strand is + → conflict (high F1R2 suggests - strand)
    - pct_f1r2 <= (1-rate) AND strand is - → conflict (low F1R2 suggests + strand)

    For fr-secondstrand (SR):
    - pct_f1r2 >= rate AND strand is - → conflict (high F1R2 suggests + strand)
    - pct_f1r2 <= (1-rate) AND strand is + → conflict (low F1R2 suggests - strand)

    For unstranded: No conflict detection (always False).

    Args:
        input_col (str): Name of input column with strand information (+ or -).
        new_col (str): Name of output column for conflict flag (boolean).
        f1r2_pct_col (str): Name of column with F1R2 percentage (0 to 1).
        rate (float): Threshold rate for conflict detection (typically 0.5 for
            majority-based conflict detection).
        strandedness (str): Library strandedness type.

    Returns:
        pl.Expr: Polars expression that evaluates to True when a conflict is detected.
    """
    mapping = _get_strand_mapping(strandedness)
    if mapping is None:
        return pl.lit(False).alias(new_col)

    high_strand, low_strand = mapping
    # Conflict: F1R2 bias says one strand, but GTF says the opposite
    return (
        pl.when(
            ((pl.col(f1r2_pct_col) >= rate) & (pl.col(input_col) == low_strand))
            | (
                (pl.col(f1r2_pct_col) <= (1 - rate))
                & (pl.col(input_col) == high_strand)
            )
        )
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias(new_col)
    )


def detect_conflict(
    df: pl.DataFrame, bias_rate: float = 0.5, strandedness: str = "fr-firststrand"
):
    """Detect conflicts between GTF-assigned strand and F1R2/F2R1 bias.

    Compares the clarified strand assignments with the F1R2/F2R1 read
    orientation bias to identify variants where these two sources of strand
    information disagree.
    Creates four conflict flag columns corresponding to the four clarified
    strand columns.

    Args:
        df (pl.DataFrame): Polars DataFrame with variant and clarified strand
            information, including the four strand_*_clarified columns and
            pct_f1r2/pct_f1r2_alt.
        bias_rate (float, optional): Threshold for conflict detection. Default
            is 0.5, meaning any majority bias (>50%) in the opposite direction
            triggers a conflict.
        strandedness (str, optional): Library strandedness type. One of
            "fr-firststrand", "fr-secondstrand", or "unstranded". Default is
            "fr-firststrand".

    Returns:
        pl.DataFrame: DataFrame with four additional boolean columns:
            - conflict_all_clarified: Conflict for strand_all_clarified
            - conflict_all_clarified_alt: Conflict for strand_all_clarified_alt
            - conflict_majority_clarified: Conflict for strand_majority_clarified
            - conflict_majority_clarified_alt: Conflict for strand_majority_clarified_alt
    """
    return df.with_columns(
        _detect_conflict(
            "strand_all_clarified",
            "conflict_all_clarified",
            "pct_f1r2",
            bias_rate,
            strandedness,
        ),
        _detect_conflict(
            "strand_all_clarified_alt",
            "conflict_all_clarified_alt",
            "pct_f1r2_alt",
            bias_rate,
            strandedness,
        ),
        _detect_conflict(
            "strand_majority_clarified",
            "conflict_majority_clarified",
            "pct_f1r2",
            bias_rate,
            strandedness,
        ),
        _detect_conflict(
            "strand_majority_clarified_alt",
            "conflict_majority_clarified_alt",
            "pct_f1r2_alt",
            bias_rate,
            strandedness,
        ),
    )


# %%
def prs2grs(prs, drop_cols=None):
    """Convert PyRanges object to GenomicRanges object with coordinate system conversion.

    PyRanges uses 0-based half-open intervals [start, end), while GenomicRanges
    uses 1-based closed intervals [start, end]. This function performs the necessary
    conversion by adding 1 to all start positions.

    Column name mappings:
    - Chromosome -> seqnames
    - Start -> starts (with +1 adjustment)
    - End -> ends
    - Strand -> strand

    Args:
        prs (pr.PyRanges): PyRanges object to convert.
        drop_cols (list, optional): List of column names to drop from the result.
            Useful for removing PyRanges-specific columns that aren't needed.

    Returns:
        GenomicRanges: GenomicRanges object with 1-based coordinate system.
    """
    tmp: pd.DataFrame = prs.as_df().rename(
        columns={
            "Chromosome": "seqnames",
            "Start": "starts",
            "End": "ends",
            "Strand": "strand",
        }
    )
    if drop_cols is not None:
        tmp = tmp.drop(columns=drop_cols)
    tmp["starts"] = tmp["starts"] + 1

    return GenomicRanges.from_pandas(tmp)


# %%
def main():
    """Main function to assign strand information to RNA SNVs.

    Workflow:
    1. Parse command line arguments and configure logging
    2. Load VCF file for the specified sample
    3. Load GTF annotations (pickled PyRanges object)
    4. Extract F1R2/F2R1 counts from VCF and calculate strand bias metrics
    5. Extend transcript annotations by the specified amount to capture nearby
    variants
    6. Overlap variant positions with extended transcript features
    7. Assign strand based on GTF annotation (strand_all and strand_majority)
    8. Clarify ambiguous strand assignments using F1R2/F2R1 bias
    9. Detect conflicts between GTF and F1R2/F2R1-based strand assignments
    10. Write results to TSV file

    Input files:
    - VCF file: {caller}/{sample}/{sample}.snvs.vcf
    - GTF pickle: {gtf}.pkl

    Output file:
    - TSV file: {caller}/{sample}/{sample}.snvs.strand.tsv

    The output TSV contains:
    - Variant identifiers (chrom, pos, id, ref, alt)
    - F1R2/F2R1 counts and percentages
    - GTF-based strand assignments
    - Clarified strand assignments (4 versions)
    - Conflict flags (4 versions)
    """
    path_vcf = snakemake.input[0]  # type: ignore # noqa: F821
    path_pickle = snakemake.input[1]  # type: ignore # noqa: F821

    out_tsv = snakemake.output[0]  # type: ignore # noqa: F821

    rate_bias = snakemake.params[0]  # type: ignore # noqa: F821
    rate_conflict = snakemake.params[1]  # type: ignore # noqa: F821
    extend_transcript = snakemake.params[2]  # type: ignore # noqa: F821
    strandedness = snakemake.params[3]  # type: ignore # noqa: F821

    path_log = snakemake.log[0]  # type: ignore # noqa: F821

    sample = snakemake.wildcards.sample  # type: ignore # noqa: F821

    configure_logger(console_output=False, log_file=path_log, log_level="INFO")

    logging.info(f"Strandedness of sample '{sample}': {strandedness}")
    logging.info(
        f"Assigning strand information for sample '{sample}' using GTF pickle '{path_pickle}'."
    )

    with open(path_pickle, "rb") as f:
        gtf = pickle.load(f)

    prs_gtf: pr.PyRanges = gtf[gtf.Feature == "transcript"]
    prs_gtf_extended = prs_gtf.extend(extend_transcript)
    grs_gtf = prs2grs(prs_gtf_extended, drop_cols=["exon_number", "exon_id"])

    df = get_vcf_data(path_vcf, sample)

    grs_vcf = GenomicRanges.from_pandas(
        pl.DataFrame(
            {
                "seqnames": df["chrom"].to_list(),
                "starts": df["pos"].to_list(),
                "ends": df["pos"].to_list(),
            }
        ).to_pandas()
    )

    df_strand = get_strand(grs_vcf, grs_gtf)
    df = df.with_row_index().join(df_strand, on="index", how="left").drop("index")
    df = clarify_strand(df, bias_rate=rate_bias, strandedness=strandedness)
    df = detect_conflict(df, bias_rate=rate_conflict, strandedness=strandedness)

    df.write_csv(out_tsv, separator="\t", include_header=True)


# %%
if __name__ == "__main__":
    main()


# %%
