PARAMETERS_CHECK = [
    "gtf",
    "fasta",
    "fasta_transcriptome",
    "polymorphism_known",
    "dbsnp",
    "pon",
    "resource_germline",
]

COLS_CHECK = {"dna_control_bam", "dna_sample_name"}

RULES = [
    "apply_bqsr",
    "base_recalibrator",
    "calculate_contamination",
    "convert_snpeff",
    "convert_vep",
    "create_sequence_dictionary",
    "download_snpeff_cache",
    "download_vep_cache",
    "extract_annotations",
    "fastp_paired_end",
    "fastp_single_end",
    "fastqc",
    "filter_mutect_calls",
    "format_haplotypecaller",
    "get_pileup_summaries",
    "get_pileup_summaries_dna",
    "gtf_to_bed_transcript",
    "haplotypecaller",
    "hard_filter",
    "learn_read_orientation_model",
    "mark_duplicates",
    "multiqc",
    "mutect2",
    "salmon",
    "salmon_index",
    "samtools_faidx",
    "slop_bed",
    "snpeff",
    "snpeff_check",
    "split_n_cigar_reads",
    "star",
    "star_index",
    "vep",
    "vep_check",
]
