dir_run: /home/user/projects/project_a/analysis/rnaseq
dir_data: /home/user/projects/project_a/data/rnaseq

mapper: star
quantifier: salmon
annotators:
  - vep
  - snpeff

species: homo_sapiens
genome: GRCh38

index_salmon: /home/user/doc/reference/salmon
index_star: /home/user/doc/reference/star_2.7.11b

gtf: /home/user/doc/reference/gtf/gencode.v44.annotation.gtf
fasta: /home/user/doc/reference/fasta/GRCh38.primary_assembly.genome.fa
fasta_transcriptome: /home/user/doc/reference/fasta/gencode.v44.transcripts.fa

polymorphism_known:
  - /home/user/doc/reference/igenomes/gatk/GRCh38/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz
  - /home/user/doc/reference/igenomes/gatk/GRCh38/Annotation/GATKBundle/beta/Homo_sapiens_assembly38.known_indels.vcf.gz
  - /home/user/doc/reference/igenomes/gatk/GRCh38/Annotation/GATKBundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  - /home/user/doc/reference/igenomes/gatk/GRCh38/Annotation/GATKBundle/1000G_omni2.5.hg38.vcf.gz

dbsnp: /home/user/doc/reference/igenomes/gatk/GRCh38/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz

check_annotations: false
cache_vep: /home/user/.vep
cache_snpeff: /home/user/doc/snpeff
version_vep: 114
version_snpeff: "105"

min_reads: 3
min_coverage: 10

suffixes_fastq:
  paired-end:
    - "_R1.fq.gz"
    - "_R2.fq.gz"
  single-end: ".fq.gz"

clean_fq: true

run_multiqc: true
