quantification: true
mutation: true

dir_run: /projects/project_xxx/analysis/rnaseq
dir_data: /projects/project_xxx/data/rnaseq

mapper: star
quantifier: salmon
annotators:
  - vep
  - snpeff

species: homo_sapiens
genome: GRCh38

index_salmon: /doc/tool/quantifier/salmon/GRCh38
index_star: /doc/tool/mapper/star/GRCh38

gtf: /doc/ref/GRCh38/gtf/gencode.v44.annotation.gtf
fasta: /doc/ref/GRCh38/fasta/GRCh38.primary_assembly.genome.fa
fasta_transcriptome: /doc/ref/GRCh38/fasta/gencode.v44.transcripts.fa

slop_transcript: 0.2

polymorphism_known:
  - /doc/db/igenomes/gatk/GRCh38/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz
  - /doc/db/igenomes/gatk/GRCh38/Annotation/GATKBundle/beta/Homo_sapiens_assembly38.known_indels.vcf.gz
  - /doc/db/igenomes/gatk/GRCh38/Annotation/GATKBundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  - /doc/db/igenomes/gatk/GRCh38/Annotation/GATKBundle/1000G_omni2.5.hg38.vcf.gz

dbsnp: /doc/db/igenomes/gatk/GRCh38/Annotation/GATKBundle/dbsnp_146.hg38.vcf.gz
pon: /doc/db/igenomes/gatk/GRCh38/Annotation/GATKBundle/1000g_pon.hg38.vcf.gz
resource_germline: /doc/db/igenomes/gatk/GRCh38/Annotation/GATKBundle/af-only-gnomad.hg38.vcf.gz

check_annotations: false
cache_vep: /.vep
cache_snpeff: /doc/tool/annotator/snpeff
version_vep: 114
version_snpeff: "105"

min_reads: 3
min_coverage: 10
min_qual_mapping: 20

suffixes_fastq:
  paired-end:
    - "_R1.fq.gz"
    - "_R2.fq.gz"
  single-end: ".fq.gz"

clean_fq: true
run_fastqc: true
run_multiqc: true

args_extra:
  haplotypecaller: "--annotation OrientationBiasReadCounts"
  mutect2: "--tumor-lod-to-emit 2"
  filter_mutect_calls: "-read-filter NotSupplementaryAlignmentReadFilter"
