dir_run: /home/mjhk/projects/data/sra/PRJNA1192192
dir_data: /home/mjhk/projects/data/sra/PRJNA1192192

index_salmon: /home/mjhk/doc/reference/salmon/index

suffix_fastq:
  paired-end:
    - "_R1.fq.gz"
    - "_R2.fq.gz"
  single-end: ".fq.gz"

clean_fq: true

run_multiqc: false
